export const inputElements = [
  {
    id: "employee_full_name",
    name: "Employee Full Name",
    type: "text",
    required: true,
    placeHolder: "Employee Full Name",
  },
  {
    id: "employee_last_name",
    name: "Employee Last Name",
    type: "text",
    required: true,
    placeHolder: "Employee Last Name",
  },
  {
    id: "employee_signature",
    name: "Employee Signature",
    type: "text",
    required: true,
    placeHolder: "Employee Signature",
  },
  {
    id: "employee_email",
    name: "Employee Email",
    type: "text",
    required: true,
    placeHolder: "Employee Email",
  },
  {
    id: "employee_title",
    name: "Employee Title",
    type: "text",
    required: true,
    placeHolder: "Employee Title",
  },
  {
    id: "employee_hourly_salary",
    name: "Employee Hourly/Salary",
    type: "text",
    required: true,
    placeHolder: "Employee Hourly/Salary",
  },
  {
    id: "exempt_non_exempt",
    name: "Exempt/Non-exempt",
    type: "text",
    required: true,
    placeHolder: "Exempt/Non-exempt",
  },
  {
    id: "employee_pay_frequency",
    name: "Employee Pay Frequency",
    type: "text",
    required: true,
    placeHolder: "Employee Pay Frequency",
  },
  {
    id: "employee_job_duties",
    name: "Employee Job Duties",
    type: "text",
    required: true,
    placeHolder: "Employee Job Duties",
  },
  {
    id: "place_to_report_on_1st_day",
    name: "Place to report on 1st Day",
    type: "text",
    required: true,
    placeHolder: "Place to report on 1st Day",
  },
  {
    id: "employer_signatory_name",
    name: "Employer Signatory Name",
    type: "text",
    required: true,
    placeHolder: "Employer Signatory Name",
  },
  {
    id: "employer_signatory_title",
    name: "Employer Signatory Title",
    type: "text",
    required: true,
    placeHolder: "Employer Signatory Title",
  },
  {
    id: "employer_signature",
    name: "Employer Signature",
    type: "text",
    required: true,
    placeHolder: "Employer Signature",
  },
  {
    id: "full_work_site_address",
    name: "Full Work Site Address",
    type: "text",
    required: true,
    placeHolder: "Full Work Site Address",
  },
  {
    id: "worksite_street",
    name: "Worksite Street",
    type: "text",
    required: true,
    placeHolder: "Worksite Street",
  },
  {
    id: "worksite_apt_suite",
    name: "Worksite Apt, Suite",
    type: "text",
    required: true,
    placeHolder: "Worksite Apt, Suite",
  },
  {
    id: "worksite_city",
    name: "Worksite City",
    type: "text",
    required: true,
    placeHolder: "Worksite City",
  },
  {
    id: "worksite_state",
    name: "Worksite State",
    type: "text",
    required: true,
    placeHolder: "Worksite State",
  },
  {
    id: "work_site_zip_code",
    name: "Work Site Zip code",
    type: "text",
    required: true,
    placeHolder: "Work Site Zip code",
  },
  {
    id: "employee_compensation",
    name: "Employee Compensation",
    type: "text",
    required: true,
    placeHolder: "Employee Compensation",
  },
  {
    id: "employee_position",
    name: "Employee Position",
    type: "text",
    required: true,
    placeHolder: "Employee Position",
  },
  {
    id: "employee_start_date",
    name: "Employee Start Date",
    type: "text",
    required: true,
    placeHolder: "Employee Start Date",
  },
  {
    id: "offer_expiration_date",
    name: "Offer Expiration Date",
    type: "text",
    required: true,
    placeHolder: "Offer Expiration Date",
  },
  {
    id: "employee_supervisor",
    name: "Employee Supervisor",
    type: "text",
    required: true,
    placeHolder: "Employee Supervisor",
  },
  {
    id: "employee_department",
    name: "Employee Department",
    type: "text",
    required: true,
    placeHolder: "Employee Department",
  },
  {
    id: "company_name",
    name: "Company Name",
    type: "text",
    required: true,
    placeHolder: "Company Name",
  },
  {
    id: "offer_sent_date",
    name: "Offer Sent Date",
    type: "text",
    required: true,
    placeHolder: "Offer Sent Date",
  },
  {
    id: "employee_signature_date",
    name: "Employee Signature Date",
    type: "text",
    required: true,
    placeHolder: "Employee Signature Date",
  },
  {
    id: "full_time_part_time",
    name: "Full Time/Part Time",
    type: "text",
    required: true,
    placeHolder: "Full Time/Part Time",
  },
];
